name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install --user hatch
          hatch run ci
